### ISSUE TITLE
Background Image options for components

### ISSUE THREAD

**Issue by parthjoshi90** [pydantic/FastUI#101]
First of all, I would like to thank you for this beautiful package.

As given in the demo examples and as I tried in my local system, it is not possible to have the background image for components like `Divs` and `Page` or full page Background image.

Is it suggestible to have another `link` stage (to load custom CSS) added by overwriting the `prebuilt_html` function?

 Thanks in advance

**Comment by samuelcolvin** [comment]
happy to allow custom CSS in `prebuilt_html`, or you can write your own method, that part is not very complicated.

**Comment by samuelcolvin** [comment]
See #102.
