### ISSUE TITLE
Textarea HTML element

### ISSUE THREAD

**Issue by sparfenyuk** [pydantic/FastUI#116]
How can I render <textarea/> instead of \<input type=text/\> in the form?

**Comment by samuelcolvin** [comment]
Not yet possible, we need to add or edit an existing component.

**Comment by hasansezertasan** [comment]
> Not yet possible, we need to add or edit an existing component.

Great work 🚀

Doesn't Custom component from #88 allow us to make it happen?

**Comment by samuelcolvin** [comment]
Well yes, but you can't yet get a textarea in a form defined from a pydantic model, that works be the big advantage.

**Comment by GChristen** [comment]
First: like lots of people have mentioned: thank you! What a helpful project. 

Is the conclusion above for a textarea within a form also true for a table? Namely that you can't currently render a custom component within a table cell?
