### ISSUE TITLE
Sample code in README gives error because of a change 3 weeks ago of definition of Table

### ISSUE THREAD

**Issue by aekespong** [pydantic/FastUI#126]
Error in sample code in README.

![image](https://github.com/pydantic/FastUI/assets/43400207/b4cf9db1-9c97-4869-815c-9290c00fc683)

Sample code doesn't work. 

Sample code gives Request Error:

![image](https://github.com/pydantic/FastUI/assets/43400207/e60b359f-4053-4c5f-911d-5659440341d5)

**Comment by aekespong** [comment]
I've solved this in PR #124

**Comment by aekespong** [comment]
Strange. Are you using the code from README?

The error is something around Typing.Generics:

`... <error not included>
File "/root/FastUI/main/env310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/FastUI/main/env310/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/FastUI/main/sample/main.py", line 38, in users_table
    c.Table[User](  # c.Table is a generic component parameterized with the model used for rows
  File "/root/FastUI/main/env310/lib/python3.10/site-packages/pydantic/main.py", line 634, in __class_getitem__
    raise TypeError(f'{cls} cannot be parametrized because it does not inherit from typing.Generic')
TypeError: <class 'fastui.components.tables.Table'> cannot be parametrized because it does not inherit from typing.Generic`

**Comment by AliRn76** [comment]
Yes you are right but the latest version is 0.3.0 and these changes have not been released yet, so maybe we can change the readme after the release of the new version 👍🏽

**Comment by hasansezertasan** [comment]
@AliRn76 It's merged 😢 and now the README.md example doesn't work with the latest version.

**Comment by samuelcolvin** [comment]
This project is a work in progress, code being wrong in readme for a few hours really isn't worth worrying about.
