### ISSUE TITLE
shadcn ui

### ISSUE THREAD

**Issue by bitnom** [pydantic/FastUI#127]
I love Python. I know Javascript and typescript. I know very little about react because it always looked really annoying to me. I recently watched a video about https://ui.shadcn.com . I'm wondering if I can use these components with FastUI, and if perhaps someone might want to create an example of integrating this. Of course my expectations are low at this early stage.

**Comment by samuelcolvin** [comment]
You could build a alternative frontend with shadcn/radix, you can use the bootstrap implementation as an example.

BTW shadcn and radix don't really give you components, they give you example code to copy & paste, hence the enormous flexibility.

**Comment by samuelcolvin** [comment]
No response.

**Comment by jlia0** [comment]
sorry to ask in this issue - but how can I build an alternative frontend?

**Comment by samuelcolvin** [comment]
Start by copying bootstrap. Come back to me if you have specific questions.
