### ISSUE TITLE
component type: "Footer" on https://fastui-demo.onrender.com/

### ISSUE THREAD

**Issue by pleabargain** [pydantic/FastUI#135]
export function unreachable(msg: string, unexpectedValue: never, args?: any) {
  console.warn(msg, { unexpectedValue }, args)
}

![image](https://github.com/pydantic/FastUI/assets/640846/b15fc82d-2e54-438c-a074-c763b1bc83db)

**Comment by samuelcolvin** [comment]
fixed.
