### ISSUE TITLE
pagination component - can't go to page '1'

### ISSUE THREAD

**Issue by tim-habitat** [pydantic/FastUI#142]
when on the cities pagination example in the demo app can't go back to page 1 when on another page.

**Comment by samuelcolvin** [comment]
Nice find, I'll look soon.

**Comment by parthjoshi90** [comment]
I found an issue here

![Screenshot from 2024-01-03 00-16-11](https://github.com/pydantic/FastUI/assets/18608298/9981ff2c-d374-4155-8260-3cd07152a7e6)

Do we need this condition?
https://github.com/pydantic/FastUI/blob/main/src/npm-fastui-bootstrap/src/pagination.tsx#L86-L90

I got the correct behavior when I added the `onClick = { type: 'go-to', query: {page} }` in place of `onClick = { type: 'go-to', query: {} }`. I guess the page represents the page number and not the total number of pages in the pagination, am I right?
