### ISSUE TITLE
422 Unprocessable Entity when submitting a single item for a multiple select input

### ISSUE THREAD

**Issue by hillstub** [pydantic/FastUI#151]
Kudos on making such a nice library!!

I just came across something that I think is a bug.

When I make a form with e.g.
```python
class SelectForm(BaseModel):
    orfs: list[str] = Field(json_schema_extra={'search_url': '/api/loci/search'})

```

I'm getting the 422 error when submitting the form and I've only selected one item. When I'm selecting multiple items it goes through.
This also happens with the demo page on https://fastui-demo.onrender.com/forms/select

**Comment by schatimo** [comment]
Duplicate to #122.
