### ISSUE TITLE
Use different path for UI API

### ISSUE THREAD

**Issue by varadinov** [pydantic/FastUI#152]
Hi,
I'm trying to create a FastAPI project that contains both REST API and UI. I would like the API to be served on /api and respectively the UI to be served on /ui and the API for the UI to be served in /ui/api. This way the application will be able to provide API for external services.
Currently I don't see an option to set a path for the API for the UI in prebuilt_html.

P.S. Is there a discord server or other option for community communication for FastUI?

**Comment by hasansezertasan** [comment]
Related to #134

**Comment by samuelcolvin** [comment]
I agree duplicate of #134.

There's no discord server, I find they're a time sink for the maintainer.
