### ISSUE TITLE
Trying to make the demo work

### ISSUE THREAD

**Issue by skullcrash** [pydantic/FastUI#167]
I wanted to try the demos in an existing fastapi docker system.
I downloaded the content of the demos folder to try the demo.
First, I changed
`from .shared import demo_page`
into
`from shared import demo_page`
(I don't know why, but I don't need the '.' it seems)
Second, I changed
`router = APIRouter()`
into
`app = FastAPI()`
(and renamed 'router' to 'app')
After that, fastapi is running but when I check the home page I get only json data.
I don't see in the code where the html is rendered. Where is it ?
Any idea why I have this problem ?
![image](https://github.com/pydantic/FastUI/assets/146533978/2d02f8d9-a26c-4a05-96ac-84ca32bc4e62)

**Comment by rgimen3z** [comment]
have you tried following the instructions in the README within the `demo` module?

**Comment by samuelcolvin** [comment]
The demo works fine for me - clone the repo, install stuff, run `make dev`.

If you're having trouble running it in docker, that's not an issue with FastUI.
