### ISSUE TITLE
Is it supports charts and complex application

### ISSUE THREAD

**Issue by prasadkumar0590** [pydantic/FastUI#169]
Hi Team,

This framework is awesome.

1. I want to create charts like line, bar and maps using this framework. I checked in components section there is no related component.
2. I want to create multi page application is it supports
3. How can we redirect one page to another page

I know it still in development pace if any alternatives please let me know

Your suggestions are appreciated

**Comment by samuelcolvin** [comment]
Thanks so much.

> I want to create charts like line, bar and maps using this framework. I checked in components section there is no related component.

See #75.

> I want to create multi page application is it supports

I'm not sure what you mean by "multi page", I would say the demo is "multi page", if that's not what you mean, please be more specific.

> How can we redirect one page to another page

Use 

https://github.com/pydantic/FastUI/blob/c3cacbb0361b688183522aa5e1d4856bcccfdc15/src/python-fastui/fastui/events.py#L17

We won't be adding proper documentation to FastUI until it's more stable, so you'll need to read the code to understand FastUI for now.
