### ISSUE TITLE
Form Methods

### ISSUE THREAD

**Issue by Chops91** [pydantic/FastUI#171]
BaseForm only allows POST, GOTO and GET methods, defaults to POST. Any intention to expand this to include DELETE and PATCH?

https://github.com/pydantic/FastUI/blob/cec25c61a7cc5a716d05d21039f95be3e8dac0e8/src/python-fastui/fastui/components/forms.py#L74

**Comment by samuelcolvin** [comment]
Well you can't submit an HTML form with any method other than `POST` AFAIK, so I'm not sure what it would mean to support `PATCH` or `DELETE` here?

Happy to consider adding it if it makes sense.

**Comment by Chops91** [comment]
Hmmm seems you are correct about the inner workings of HTML form methods. Looking a bit further into this it seems that it is possible to set a field with name `_METHOD` as a hidden field of the form which is set to a method other than `GET` or `POST`. Refer to this SO question https://stackoverflow.com/questions/53312224/form-method-put-in-html-with-php

Essentially what I am trying to achieve is that with an existing FastAPI app I have some endpoint/s against the delete, and patch methods. Implementing FastUI with said app some refactoring is required as the endpoints against `DELETE` and `PATCH` methods now need to be `POST` methods with `/delete` and `/patch' suffixed to the API paths. The refactoring could be anything different in the existing path really but something making it identifiable what action needs to be taken.

Use case for patch is I have a user (could be anything) with some data in my database. User get's married, changes their last name, relocates, whatever, they are presented with a form to update their information. This form when submitted ideally hits an API endpoint with a `PATCH` HTTP request, rather than a `POST` request with `/update` on the suffix of the path.

Use case for the delete is potentially a bit more exotic. Essentially to bring up a double check with the user prior to the client sending the delete request to the server. The form is a modal with a tick box saying "Yes I am sure I want to do this". This form when submitted ideally hits an API endpoint with a `DELETE` HTTP request, rather than a `POST` request with `/delete` on the suffix of the path.

**Comment by samuelcolvin** [comment]
Thinking about this a bit more, I agree we need a way to make delete/patch/put etc. requests. But I don't think it needs to be linked or related to forms.

I'll try to have a go at creating a PR.

**Comment by samuelcolvin** [comment]
I think we need a new component defined thus:

```py

class Fetch(_p.BaseModel, extra='forbid'):
    # if no trigger, the request is made as soon as the component is mounted
    trigger: _t.Union[events.PageEvent, None] = None
    # components to show while the request is in progress
    progress_components: '_t.List[AnyComponent]' = _p.Field(default=[], serialization_alias='loadingComponents')
    on_complete: _t.Union[events.AnyEvent, None] = _p.Field(default=None, serialization_alias='onComplete')
    path: str
    method: _t.Literal['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'] = 'GET'
    # if the trigger event has context, it will be merged with json_body
    json_body: _t.Union[_t.Dict[str, _t.Any], None] = _p.Field(None, serialization_alias='jsonBody')
    headers: _t.Union[_t.Dict[str, str], None] = None
    type: _t.Literal['Fetch'] = 'Fetch'
```

I don't have time to work on this right now, but happy to review a PR to implement this, or I'll get to it soon.
