### ISSUE TITLE
Select description gets attached to multiple field

### ISSUE THREAD

**Issue by tim-habitat** [pydantic/FastUI#178]
In the demo [here](https://github.com/pydantic/FastUI/blob/bb4fb360b7c2ccbae290bcd6a89d33813f6f59bb/demo/forms.py#L124) if we add a description to the first select as:
```python
class SelectForm(BaseModel):
    select_single: ToolEnum = Field(title='Select Single', description="First selector")
    select_multiple: list[ToolEnum] = Field(title='Select Multiple')
    search_select_single: str = Field(json_schema_extra={'search_url': '/api/forms/search'})
    search_select_multiple: list[str] = Field(json_schema_extra={'search_url': '/api/forms/search'})
```
it produces the following, where we can see the description leaking to the next select:
![image](https://github.com/pydantic/FastUI/assets/86600518/2494cfe8-5e18-47d2-bfe0-45c6b77d62af)

However, I noticed that if I use a different `Enum` for the second selector this does not happen; e.g:
```python
class ToolEnum2(str, enum.Enum):
    hammer = 'hammer'
    screwdriver = 'screwdriver'
    saw = 'saw'
    claw_hammer = 'claw_hammer'

class SelectForm(BaseModel):
    select_single: ToolEnum = Field(title='Select Single', description="First selector")
    select_multiple: list[ToolEnum2] = Field(title='Select Multiple')
    search_select_single: str = Field(json_schema_extra={'search_url': '/api/forms/search'})
    search_select_multiple: list[str] = Field(json_schema_extra={'search_url': '/api/forms/search'})
```
![Screenshot 2024-02-09 at 17 59 48](https://github.com/pydantic/FastUI/assets/86600518/fda48a30-df26-4ebd-a5c5-c01425324e40)

Note: adding a description to the second select in the initial case doesn't work either, the first description still keeps it spot:
```python
class SelectForm(BaseModel):
    select_single: ToolEnum = Field(title='Select Single', description="First selector")
    select_multiple: list[ToolEnum] = Field(title='Select Multiple', description="Second selector")
    search_select_single: str = Field(json_schema_extra={'search_url': '/api/forms/search'})
    search_select_multiple: list[str] = Field(json_schema_extra={'search_url': '/api/forms/search'})
```
![image](https://github.com/pydantic/FastUI/assets/86600518/f87dbdb4-abed-4720-b7ac-f52d0a951e67)

my 2 cents; I believe the description gets attached to the components by it's name and the component name is derived by the `Enum` name - though i am unsure how to solve it for now

**Comment by samuelcolvin** [comment]
Thanks for reporting, this looks like a bug.

Based on the output from the follwing the bug doesn't seem to be in Pydantic, but rather in FastUI.

PR welcome to fix this

```pyimport enum

from pydantic import BaseModel, Field
from devtools import debug


class ToolEnum(str, enum.Enum):
    hammer = 'hammer'
    screwdriver = 'screwdriver'
    saw = 'saw'
    claw_hammer = 'claw_hammer'


class SelectForm(BaseModel):
    select_single: ToolEnum = Field(title='Select Single', description='First selector')
    select_multiple: list[ToolEnum] = Field(title='Select Multiple')
    search_select_single: str
    search_select_multiple: list[str]


debug(SelectForm.model_json_schema())
```
