### ISSUE TITLE
named styles

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/FastUI#22]
The idea is to provide something a bit like [bootstrap's](https://getbootstrap.com/docs/4.0/components/buttons/) "primary", "secondary", "success" etc. to customise components without resorting the the sledge hammer of CSS.

I think we have:
* `primary` - default
* `secondary` - for "not the main thing to do"
* `warning` - for "this does bad/irreversible" stuff

That should be enough for now.

**Comment by samirdhoran2000** [comment]
Hii @samuelcolvin  can you tell me briefly about this issue
