### ISSUE TITLE
State is needed!

### ISSUE THREAD

**Issue by ManiMozaffar** [pydantic/FastUI#230]
A big problem with this idea is that there is no persistent and in memory state.
Think of this scenario, I made a list for our operation team. The table I've rendered using FastUI return 100 million data.
Each time they go to next page, the count is returned by the API, that's the problem. server side rendering ends up returning similar data in every response, which is not very efficient.
Eventually that can be solved by having on_click on pagination obj. but my point is that you end up adding it to everywhere, and it might be even better to sometime have that as persistent state and make it eventually consistent.
I understand that FastUI is still work in progress, but that's just a question for me to see if this has been thought and considered? if so, what would be the plan to solve this problem?

SSR might/will run into same problem as OOP langauges;
You need to show a banana, but you render a big jungle, in which there's a monkey holding a banana.

**Comment by samuelcolvin** [comment]
This is a dumb way to create an issue.

Please don't use exclamation marks, please do you research.

State exists!

**Comment by ManiMozaffar** [comment]
Ofc state exists, but I couldn't find a way to manipulate state from the python library without writing react. 
**Did my research**, not in example nowhere else the problem I mentioned has been solved efficiently. 
The only solution I found was **_ServerLoad_** which does not solve the problem with eventually consistency.
