### ISSUE TITLE
hope fastui is as easy to use as Streamlit

### ISSUE THREAD

**Issue by dyuzhou** [pydantic/FastUI#239]
I am currently using a combination of fastapi + Streamlit. Streamlit can quickly complete beautiful pages, AI dialogues and display of charts. It has good support for pandas, but Streamlit is too slow. Does fastui have plans to support convenient chart display like Streamlit?
+ [gallery](https://streamlit.io/gallery?category=data-visualization)
+ [streamlit components](https://streamlit.io/components)

**Comment by hasansezertasan** [comment]
I believe you should update the issue title with the question 😇.

#75 might have an answer to your question, please check it out 🚀.

**Comment by dyuzhou** [comment]
It certainly seems so
