### ISSUE TITLE
multi-select form doesn't allow selection of only one item

### ISSUE THREAD

**Issue by fmrib00** [pydantic/FastUI#251]
it gives "422 Unprocessable Entity"

![image](https://github.com/pydantic/FastUI/assets/100891554/c7523ee0-9bbb-487b-9c7f-9744f374d49a)

**Comment by tuirennder** [comment]
Same as https://github.com/pydantic/FastUI/issues/122

**Comment by sydney-runkle** [comment]
Closing as a duplicate.

**Comment by sydney-runkle** [comment]
Fixed by https://github.com/pydantic/FastUI/pull/141
