### ISSUE TITLE
Filters with date doesn't get submitted to table search query

### ISSUE THREAD

**Issue by ManiMozaffar** [pydantic/FastUI#254]
I have a column in my filter in table, which is DATE.

<img width="359" alt="Screenshot 2024-03-21 at 16 31 55" src="https://github.com/pydantic/FastUI/assets/86913668/644036ee-1704-407d-b94b-30889abb9d0d">

When I click and choose a date, it doesn't send a new GET request to the API, unlike all other fields.
Although it'd be sent if i choose another field and change its value.
I believe it's being saved correctly, but its state isn't handled after being modified.

**Comment by sydney-runkle** [comment]
I believe this should be fixed by https://github.com/pydantic/FastUI/pull/261, so closing this as well!
