### ISSUE TITLE
Unable to run fastUI, error is name 'AnyEvent' is not defined  

### ISSUE THREAD

**Issue by qgyhd1234** [pydantic/FastUI#258]
I'm learning to use fastui, follow the tutorial, I want to write a homepage, the result is an error：pydantic.errors.PydanticUndefinedAnnotation: name 'AnyEvent' is not defined

my code：

```
......

def index() -> list[AnyComponent] :
    return [
        c.PageTitle(text=f'FastUI Demo '),
        c.Page(
            components = [
                c.Heading(text = "hello world", level=2),
            ]
        ),
    ]

@router.get("/", response_model=FastUI, response_model_exclude_none=True)
async def read_root() -> list[AnyComponent]:
    return index()

@router.get('/{path:path}', status_code=404)
async def api_404():
    # so we don't fall through to the index page
    return {'message': 'Not Found'}
......

```

**Comment by neerajadsul** [comment]
Just checked, 0.5.0 is fine. Hope this helps. If need, `pip install --upgrade fastui==0.5.0`

**Comment by qgyhd1234** [comment]
> Just checked, 0.5.0 is fine. Hope this helps. If need, `pip install --upgrade fastui==0.5.0`

Thanks, 0.5.0 works fine, 0.5.2 doesn't
