### ISSUE TITLE
Table cell color

### ISSUE THREAD

**Issue by OmelchenkoPeter** [pydantic/FastUI#267]
Hi!
Can you tell me how I can change the cell color in the table? Can I use condition for that?
Thank you

**Comment by samuelcolvin** [comment]
I didn't think right now we have a way to set class name on a per row basis right now. 

@sydney-runkle let's think about whether there a way to add this?

**Comment by OmelchenkoPeter** [comment]
@samuelcolvin @sydney-runkle Will wait! Thank you!

**Comment by sydney-runkle** [comment]
@OmelchenkoPeter,

Sure thing! Tagging this appropriately and will consider for our next milestone!

**Comment by jimkring** [comment]
#308 might allow this if what is inserted into the cell is a fastui.components.Div component with a class_name that colors the background.
