### ISSUE TITLE
GoToEvent doesn't refresh the page

### ISSUE THREAD

**Issue by charlie-corus** [pydantic/FastUI#272]
I have a landing page with a list of items, and each item has a delete button. Pressing the button pops up a modal that asks for confirmation. If the delete is confirmed, I need the landing page to refresh so that the deleted item is no longer there. 

I've tried to do this by having the `post` route handler for the delete endpoint return and fire a `GoToEvent`:

```Python
[c.FireEvent(event=GoToEvent(url='/landing_page'))]
``` 

I can change this URL and go to a different endpoint after the delete action, but if I point back to the landing page where the event was triggered, the page doesn't refresh - it still shows the deleted item and the UI is stale. Is there a way to fix this, without having the delete method route to an otherwise pointless intermediate page? 

Thanks!

**Comment by charlie-corus** [comment]
Duplicate of https://github.com/pydantic/FastUI/issues/255

**Comment by Alex-FIR-IT** [comment]
You can "reload" the page if the url is different from the first one. So, instead of creating, as you said "pointless intermediate page", you can just append a random parameter in "GoTo" event. This way, FastUI will treat it as another url:

```python3
import uuid
...
return [c.FireEvent(event=GoToEvent(url=f"/landing_page?refresh={uuid.uuid4()}"))]
    
```
