### ISSUE TITLE
demo loading failed 

### ISSUE THREAD

**Issue by HakunamatataLeo** [pydantic/FastUI#285]
<img width="1063" alt="image" src="https://github.com/pydantic/FastUI/assets/4550421/8c4fdabf-0dd2-494b-a904-88322f0c4e29">

**Comment by samuelcolvin** [comment]
@sydney-runkle is working on fastui docs, this is probably related, will be fixed soon

**Comment by sydney-runkle** [comment]
Closing as a dupe, this has been reported here: https://github.com/pydantic/FastUI/issues/282.

Will be resolved before the next release, thanks!
