### ISSUE TITLE
[Pin Me] FastUI Discussion Slack Channel

### ISSUE THREAD

**Issue by jimkring** [pydantic/FastUI#303]
FYI, there's a slack channel for FastUI Discussion here:
https://pydanticlogfire.slack.com/archives/C0720M7D31S

**Comment by jimkring** [comment]
@sydney-runkle, I was chatting with @samuelcolvin and we thought it would be a good idea to create a pinned issue to alert active contributors to the presence of this discussion slack channel.

(Feel free to pin this issue or create a new one that a pydantic team member can edit/manage)

**Comment by hasansezertasan** [comment]
I would love to join but I don't have a "@pydantic.dev" account... An invitation could be helpfull.

**Comment by jimkring** [comment]
@hasansezertasan I didn’t need anything special when I signed up from the link on this page: https://docs.pydantic.dev/logfire/help/

**Comment by hasansezertasan** [comment]
> @hasansezertasan I didn’t need anything special when I signed up from the link on this page: https://docs.pydantic.dev/logfire/help/

Thank you for pointing out this link. I'm in!

**Comment by hramezani** [comment]
Closing this issue because the link added to the readme in https://github.com/pydantic/FastUI/pull/302
