### ISSUE TITLE
computed_field properties not showing in tables

### ISSUE THREAD

**Issue by jimkring** [pydantic/FastUI#320]
I have a model with some [computed_field](https://docs.pydantic.dev/2.0/usage/computed_fields/)s and they do not show up automatically when I try to render them in a table, unless I explicitly define the `columns` of the table (and reference the field by name with a `DisplayLookup`).

The problem/inconvenience with this, is that now I have to specify every column with a DisplayLookup, just to include the one column that is a computed property. This makes my code less DRY and harder to maintain.

it would be nice if the table logic would find these computed properties and include them when the columns/fields are discovered.

**Comment by hasansezertasan** [comment]
I believe the main problem is here at the `DisplayLookup` builder logic:

https://github.com/pydantic/FastUI/blob/97c4f07af723e370039e384d240d5517f60f8062/src/python-fastui/fastui/components/tables.py#L46-L57

Computed fields are accessible by `model.model_computed_fields.items()`, check this out:

```python
from pydantic import BaseModel, computed_field


class Rectangle(BaseModel):
    width: int
    length: int

    @computed_field
    @property
    def area(self) -> int:
        return self.width * self.length


data = Rectangle(width=3, length=4)
data.model_fields.items() # Model Fields
data.model_computed_fields.items() # Computed Fields

```

**Comment by hasansezertasan** [comment]
I'll work on this tomorrow and try to come up with a proper solution 🤓.

**Comment by jimkring** [comment]
@hasansezertasan thank you for the good insights and for looking into this enhancement!

**Comment by hasansezertasan** [comment]
> @hasansezertasan thank you for the good insights and for looking into this enhancement!

You're welcome, I'm happy to be able to work on this issue 🤓.

I'd like to have your review if you got time to spare. #321
