### ISSUE TITLE
Drop Vite and embrace htmx 2.0.0?

### ISSUE THREAD

**Issue by shroominic** [pydantic/FastUI#335]
I think now with htmx 2.0.0 we can migrate to just having a python worker outputting html instead of json.

**Comment by samuelcolvin** [comment]
Duplicate of #48.

But the hard bit isn't htmx, it's the template rendering in python.

**Comment by hasansezertasan** [comment]
> I think now with htmx 2.0.0 we can migrate to just having a python worker outputting html instead of json.


Check out Ludic.
