### ISSUE TITLE
Tailwind, Bootstrap and other CSS framework support.

### ISSUE THREAD

**Issue by Almas-Ali** [pydantic/FastUI#36]
We don't need more built-in framework support. We can make a base component and others will override to use any CSS frameworks. We can't support every frameworks behaviour but the most popular ones.

**Comment by samuelcolvin** [comment]
I'm not sure what you're asking here.

It's possible to customise either the component implementation or the classes already, as we do with `fastui-bootstrap`.

I looked into using shadcn/radix for the reference implementation but it would have been a lot more work than using bootstrap which provides a lot more pre-defined.

Another advantage of bootstrap is that it uses sass/scss, and there's a good sass compiler available for in Python, so we could allow developers to customise the look of their app without needing to resort to node/npm etc.

**Comment by samuelcolvin** [comment]
see #38

**Comment by rgbkrk** [comment]
> I looked into using shadcn/radix for the reference implementation but it would have been a lot more work than using bootstrap which provides a lot more pre-defined.

What would you recommend for getting started with using shadcn/ui with FastUI? I'm using shadcn/ui with both a next.js app and a vite app which I'm really happy with. Obviously I'd need to have a package.json in the root for working with `npm`, the tailwind config, and the `components` from shadcn/ui. What's the hookup I'd need for FastUI to work fairly fluidly with it?
