### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by pkaleta** [pydantic/FastUI#367]
Hi, this looks very useful however I've noticed that it hasn't been updated for a while. Is it still maintained?

**Comment by iBuitron** [comment]
up

**Comment by dkphhh** [comment]
I have the same concern

**Comment by custodeemanuel** [comment]
same concern here

**Comment by jimkring** [comment]
I have submitted pull requests and the pydantic team has been very responsive and helpful to get them merged. This is definitely not production software at the moment, which is clearly stated by the team. If there are areas that you would like to see improved, feel free to make a pull request. If you have questions about how to use fast UI, please post them and I’m sure somebody will answer them.
