### ISSUE TITLE
Why not using Svelte to create web components?

### ISSUE THREAD

**Issue by ggbaro** [pydantic/FastUI#50]
> Always been a fan of pydantic (kudos @samuelcolvin), I'm glat to explore this new project

Have you considered making the frontend components in Svelte?
It's a pretty stable framework now, and [it can actually compile to web components](https://webcomponents.dev/docs/svelte).

Web components could be fairly easy to use with a jinja(or mini-jinja)-based templated composer (#48)

I think it could be even possible to use [Svelte stores](https://svelte.dev/docs/svelte-store) as FastUI components, allowing cool interactions between displayed contents

**Comment by ggbaro** [comment]
I can help if you think this could work

**Comment by hasansezertasan** [comment]
> But right now, I don't think there's a big win to most users from (re)writing the frontend with svelte.

I believe the community support for ReactJS and great ecosystem built arround it is a great upside.
