### ISSUE TITLE
Dynamic form components

### ISSUE THREAD

**Issue by mohandoz** [pydantic/FastUI#63]
Hi
Is there a way to create dynamic form components, for now the form field only accept
FormField = FormFieldInput | FormFieldCheckbox | FormFieldFile | FormFieldSelect | FormFieldSelectSearch

cannot use ServerLoad in the form

**Comment by hasansezertasan** [comment]
I didn't check the source code for your question but I believe that in the future, these kind of requirements will be satisfied (if it's not already) by FastUI.
