### ISSUE TITLE
Trigger server event on input set/change 

### ISSUE THREAD

**Issue by mohandoz** [pydantic/FastUI#64]
it's not just bound  choice field but ill put it as an example

ex 1: 
trigger server event when choice field selected, for my case i want to use the choice field value and filter data to generate another choice field based on it

ex 2:
Trigger server event when for example input1 and input2 are present

**Comment by sydney-runkle** [comment]
Closing for now, I believe this is supported. Please provide a more in-depth description of your request if you think otherwise!
