### ISSUE TITLE
How to style/modify existing components?

### ISSUE THREAD

**Issue by ritwickdsouza** [pydantic/FastUI#65]
With reflex.dev it's possible to pass custom css attributes to components.
Can we do the same with FastUI?

**Comment by hasansezertasan** [comment]
https://github.com/samuelcolvin/FastUI/blob/0f577cdca3441d77306717ea5a49f60acb742250/demo/tables.py#L138

Check this out!

**Comment by samuelcolvin** [comment]
Hi @ritwickdsouza you can add classes, currently we don't allow custom css styles. If lots of people really want this hack, please upvote this issue and we could add it.

**Comment by rom3ocrash** [comment]
@samuelcolvin yes definitely, actually will be great to be able to use tailwindcss 😍

**Comment by samuelcolvin** [comment]
Tailwind would work fine provided all classes are defined in the frontend, what wouldn't work (easily) is adding tailwind CSS classes from python, since by default they would be missing from the JS bundle and therefore be stripped out via PostCSS processing.
