### ISSUE TITLE
Proposal: New Syntax for components declaration

### ISSUE THREAD

**Issue by butvinm** [pydantic/FastUI#84]
I've been exploring a new way of writing FastUI components that aims to make the code shorter and easier to understand.

### Overview

The current way of writing components involves a lot of indentation and detailed structures:

```python
c.Div(
    components=[
        c.Heading(text='Link List', level=2),
        c.Markdown(
            text=(
                'This is a simple unstyled list of links, '
                'LinkList is also used in `Navbar` and `Pagination`.'
            )
        ),
        c.LinkList(
            links=[
                c.Link(
                    components=[c.Text(text='Internal Link - go to the home page')],
                    on_click=GoToEvent(url='/'),
                ),
                c.Link(
                    components=[c.Text(text='Pydantic (External link)')],
                    on_click=GoToEvent(url='https://pydantic.dev'),
                ),
            ],
        ),
    ],
    class_name='border-top mt-3 pt-1',
)
```

On the other hand, the new way simplifies things:

```python
c.Div(class_name='border-top mt-3 pt-1')[
    c.Heading(level=2)['Link List'],
    c.Markdown[
        'This is a simple unstyled list of links, '
        'LinkList is also used in `Navbar` and `Pagination`.'
    ],
    c.LinkList[
        c.Link(on_click=GoToEvent(url='/'))[
            c.Text['Internal Link - go to the home page']
        ],
        c.Link(on_click=GoToEvent(url='https://pydantic.dev'))[
            c.Text['Pydantic (External link)']
        ],
    ],
]
```

### Advantages

The new way of writing components is easier to read and requires less code. It makes the code more straightforward and easier to manage.

### Example

Take a look at how it could be implemented and used with FastUI components: [Usage with FastUI Components](https://github.com/butvinm/markpy/blob/master/examples/new.py).

### Remarks

It's crucial to recognize that this approach is highly opinionated and involves breaking changes. It's presented as a proposal, not an ideal or universally accepted solution. Consider the implications and potential challenges before adopting this syntax in a production environment.

**Comment by samuelcolvin** [comment]
How would this integrate with Pyd

**Comment by samuelcolvin** [comment]
I guess you're assuming the use of variadic generics which are 3.11+ only, but even then I'm not sure how well they're supported in Pydantic, or by IDEs.

Have you tried typing this?

**Comment by samuelcolvin** [comment]
Closing as no reply, but happy to discuss further.

**Comment by butvinm** [comment]
@samuelcolvin, sorry for the wait, and thanks for your feedback. I've just realized that `__class_getitem__` is considered a generic alias. To address that issue, we can get rid of the `Component[...]` syntax and use only subscriptions on objects. So, the previous example can be rewritten as:

```python
c.Div(class_name='border-top mt-3 pt-1')[
    c.Heading(level=2)['Link List'],
    c.Markdown()[
        'This is a simple unstyled list of links, '
        'LinkList is also used in `Navbar` and `Pagination`.'
    ],
    c.LinkList()[
        c.Link(on_click=GoToEvent(url='/'))[
            c.Text()['Internal Link - go to the home page']
        ],
        c.Link(on_click=GoToEvent(url='https://pydantic.dev'))[
            c.Text()['Pydantic (External link)']
        ],
    ],
]
```

It obviously makes the code slightly less readable but eliminates confusion with Generics. And it is supported by type checkers and IDE's as well.

**Comment by butvinm** [comment]
I've also provided an example illustrating the declaration and utilization of FastUI components. You can examine it [here](https://github.com/butvinm/markpy/blob/master/examples/fastui.py). The code successfully passes mypy type checking.
