### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by asob** [pydantic/FastUI#95]
Just wanted to say that project looks very exciting, but I'm wondering about the following:

* How to deploy a FastUI application? 
* Things to consider during deployment.
* Requirements for the server which will run the application.

**Comment by hasansezertasan** [comment]
To answer your question, first we need to take a look at how FastUI works.

Frontend: Under the hood it uses a minified JavaScript code to interpret (or compile, not sure) the specs that we define in our routes.

Backend: The rest is, regular REST. Returns JSON that contains data to be presented and the specification that explains how the data will be presented (which will be used by the frontend code).

My answers to your questions...

- I believe you don't need to do anything special to deploy a FastAPI application with FastUI, common FastAPI deployment approaches should work.
- I'm not sure for what you asked? Security issues or something else?
- Most probably same answer with the first question.

**Comment by asob** [comment]
@hasansezertasan Thanks for explanations, great that you mentioned fastAPI now I at least know where to look. But I still want to suggest you add a guide on how to deploy.

**Comment by hasansezertasan** [comment]
Happy to help. I agree, there are a lot of blank spots in the docs, there is not any (probably yet).

If that is all, can you please close the issue?
